In [1]:
import numpy as np
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [2]:
np.zeros(3)

array([0., 0., 0.])

In [3]:
np.ones(2)

array([1., 1.])

In [4]:
np.empty(4)

array([5.56216859e+141, 6.01347002e-154, 1.20336039e+132, 1.05074856e-153])

In [5]:
# with range of elements
b = np.arange(6)
b

array([0, 1, 2, 3, 4, 5])

In [6]:
c = np.arange(2,21)
c

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [7]:
d = np.arange(2,21,2)
d

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
e = np.linspace(0,20,num = 7)
e

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        ])

In [9]:
f = np.ones(5, dtype=np.int8)
f

array([1, 1, 1, 1, 1], dtype=int8)

In [10]:
# 2d array

g = np.zeros((2,3))
g

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
h = np.ones((5,6))
h

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [12]:
# 3d array

i = np.arange(24).reshape(2,3,4)
i

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [13]:
food = np.array(["Samosa","Pakora","Raita"])
food

array(['Samosa', 'Pakora', 'Raita'], dtype='<U6')

In [14]:
type(food)

numpy.ndarray

In [15]:
len(food)

3

In [16]:
food[1]

'Pakora'

In [17]:
food[1:]

array(['Pakora', 'Raita'], dtype='<U6')

In [18]:
price=np.array([3,4,5,6])
price

array([3, 4, 5, 6])

In [19]:
price.mean()

4.5

In [20]:
np.arange(1,50,7)

array([ 1,  8, 15, 22, 29, 36, 43])

In [21]:
#line space

np.linspace(20,25,40)

array([20.        , 20.12820513, 20.25641026, 20.38461538, 20.51282051,
       20.64102564, 20.76923077, 20.8974359 , 21.02564103, 21.15384615,
       21.28205128, 21.41025641, 21.53846154, 21.66666667, 21.79487179,
       21.92307692, 22.05128205, 22.17948718, 22.30769231, 22.43589744,
       22.56410256, 22.69230769, 22.82051282, 22.94871795, 23.07692308,
       23.20512821, 23.33333333, 23.46153846, 23.58974359, 23.71794872,
       23.84615385, 23.97435897, 24.1025641 , 24.23076923, 24.35897436,
       24.48717949, 24.61538462, 24.74358974, 24.87179487, 25.        ])

In [22]:
#specify ur data type

np.empty(16,dtype=np.int64)

array([23925768161198147, 32370111954616435, 28992201780691036,
       12948244072300620, 32651616996819049, 25896170311057512,
       28710924373327984, 26740556586287209, 27303510834217060,
       25896196080664693, 32651591226556520, 12948368627204207,
       29555336418492531, 29836540811477108, 30962737072111727,
       30962247445250145], dtype=int64)

# Array function

In [23]:
k = np.array([200,312,342,134,663,552,351,631,234,345])
k

array([200, 312, 342, 134, 663, 552, 351, 631, 234, 345])

In [24]:
k.sort()

In [25]:
k

array([134, 200, 234, 312, 342, 345, 351, 552, 631, 663])

In [26]:
l = np.array([12.3,45,32.23,12,31.2])
l

array([12.3 , 45.  , 32.23, 12.  , 31.2 ])

In [27]:
np.concatenate((k,l))

array([134.  , 200.  , 234.  , 312.  , 342.  , 345.  , 351.  , 552.  ,
       631.  , 663.  ,  12.3 ,  45.  ,  32.23,  12.  ,  31.2 ])

In [28]:
m = np.array([[1,2,3,4,5],[5,4,3,2,1]])
m

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [29]:
m

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [30]:
n =np.array([[2,3,4,6,7],[7,5,3,8,9]])
n

array([[2, 3, 4, 6, 7],
       [7, 5, 3, 8, 9]])

In [31]:
o = np.concatenate((m,n),axis =0)
o

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1],
       [2, 3, 4, 6, 7],
       [7, 5, 3, 8, 9]])

In [32]:
o = np.concatenate((m,n),axis =1)
o

array([[1, 2, 3, 4, 5, 2, 3, 4, 6, 7],
       [5, 4, 3, 2, 1, 7, 5, 3, 8, 9]])

# 2-D Array

In [35]:
a = np.array([[3,4],[2,1]])
a

array([[3, 4],
       [2, 1]])

In [36]:
b = np.array([[6,7],[8,9]])
b

array([[6, 7],
       [8, 9]])

In [38]:
np.concatenate((a,b))

array([[3, 4],
       [2, 1],
       [6, 7],
       [8, 9]])

In [46]:
array_example = np.array([[[0,1,2,3],[4,5,6,7]],
                [[0,1,2,3],[4,5,6,7]],
                 [[0,1,2,3],[4,5,6,7]]])
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [48]:
array_example.ndim

3

In [49]:
b = np.array([
    [5,6,7],
    [8,9,10],
    [11,12,13]
])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [53]:
#checking dimension
b.ndim

2

In [54]:
#elements of an array
array_example.size

24

In [58]:
#shape checking
array_example.shape

(3, 2, 4)

In [59]:
b.shape

(3, 3)

In [61]:
c = np.arange(9)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [63]:
#reshape
d = c.reshape(3,3)
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [65]:
np.reshape(c,newshape=(1,9),order="C")

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [66]:
#convert 1d to 2d array

a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
a.shape

(9,)

In [74]:
#row wise
b = a[np.newaxis,:]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [75]:
b.shape

(1, 9)

In [76]:
#column wise
c = a[: , np.newaxis]
c 

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [77]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
a[2:5]

array([3, 4, 5])

In [79]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [81]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [82]:
a.sum()

45

In [83]:
a.mean()

5.0